name: "Hello world"
description: "My first real add-on!"
version: "1.4.0"
slug: "hello_world"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
webui: http://[HOST]:[PORT:2839]
ports:
  8000/tcp: 2839 #POTREBNA KONFIGURACIJA ZA webui -> PORT OD CONTAINERA(8000 -> DEFINIRAN UNUTAR Dockerfile) POTREBNO MAPIRATI NA 2839 IZ webui URL-A
